### ISSUE TITLE
kubebot architecture 

### ISSUE THREAD

**Issue by PratikDhanave** [leopardslab/kubebot#3]

**Comment by Vishvajeet590** [comment]
Hi @PratikDhanave , what will be the flow of the application. I have one simple plan,  we can create a bot that users can install on their cluster and it will have options for integration with different messaging platforms. 

The bot would use dialogue flow to get intent from the conversation and we can perform those tasks on kubeCtl and respond accordingly.

Is this the high-level idea we are going to go with?

**Comment by Vishvajeet590** [comment]
@PratikDhanave  Here is a brief explanation of the my architecture proposal for kubeBot. Please give some inputs on it. I am working on chat service in meantime.

# Description

KubeBot will have microservice architecture. There are 3 main services which are responsible for the whole operation.

### Diagram

![Microservices](https://user-images.githubusercontent.com/42716731/159443122-2439c8fa-9642-4e52-bcc3-287265faeb50.png)

![Workflow](https://user-images.githubusercontent.com/42716731/159443244-203a6b14-4c47-4f1f-be65-fdc097d3c467.png)
# Kube Chat Service

It handles the incoming and outgoing messages from the user and outputs to the bot, for example user sends a message bot captures the message sends it to this, Kube chat service which initiates the process. After all the execution it will send the output message.

### Working Kube Chat Service

![Kube Chat Service](https://user-images.githubusercontent.com/42716731/159443318-cc7172d7-d2e8-489a-83e3-535e81e78449.png)

Kube chat services take the input message which contains sender platform and content. We first check if the content string is a directly executable kubectl command or not if not, It sends the message for command (intent) detection. There might be chances the user has not provided all information at once so we send back the message to the user with the context of prior command and information and ask to fill up other details like some missing arguments or files. 

Once we gather all the information we build the command in the **Command builder** and send it to Kube Executor Service.

# Kube Executor Service

Kube Executor service gets the command string as its input. We run that command on the kubectl using **os.exec** It will be run concurrently to manage crashes**.** The output of the command from Kubectl is formatted and is passed to the Kube Chat service which is sent to the bot for displaying to the user.

Kube Executor Also has a task to keep watching the deployed clusters and report back all or specified events which can occur asynchronously. For this as soon as any desired event occurs Kube Executor service will send an alert to the bot which in turn displays on the chatbox. 

# Logger Service

Describe relevant tables and views in the database. 

This service will be used by the other two services simultaneously to log the details during the operation.

**Comment by priyanshuraj400** [comment]
kubebot is a monitoring, alerting and debugging bot which is different from other available bots in the aspect that it performs 'Root Cause Analysis' on traces, logs, events and metrics generated from the kubernetes cluster. To monitor the pods/nodes health, the bot uses monitoring tool Prometheus and Grafana. To collect all the data from the cluster, Opentelemetry Collector is used in conjunction to Grafana. Otel-Col stores the data in a database which ultimately helps in 'Root Cause Analysis' and generate relavant alerts to the user.
The architecture and pipeline flow of the kubebot is as follows:

![kubebot high level architecture](https://github.com/priyanshuraj400/kubebot---GSoC-2022/blob/main/util/gsoc.jpeg?raw=true)

closes #3
